apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/spring-music-ga
    containerapp.apps.tanzu.vmware.com/class: kubernetes
  name: spring-music-ga
spec:
  contact:
    team: warroyo
  content:
    buildTimestamp: "2024-10-10T19:56:54Z"
    gitCommit: ba3767cff45128ef66b837a396ff441a33be06ea-dirty
    gitURL: github.com/warroyo/spring-music.git
    packageImage: ghcr.io/warroyo/spring-music-ga@sha256:e800bb4b421a8a6e40e357190bbc6e15079731efe28fe75d06a58a60e6bdb374
    packageRefName: spring-music-ga.apps.local
    packageVersion: 20241010.1956.54464
    summary: git:ba3767c @ 2024-10-10T19:56:54Z
    version: 20241010.1956.54464
  health:
    maxUnavailableReplicas: 10%
  image: ghcr.io/warroyo/spring-music-ga:20241010.1956.54464@sha256:4f7fbc6b9297118c0e7367945a0423fcbe5deb8b2cf036b9876085ea858af1c5
  nonSecretEnv:
  - name: JAVA_TOOL_OPTIONS
    value: -Dmanagement.endpoint.health.probes.add-additional-paths=true -Dmanagement.health.probes.enabled=true
      -Dserver.port=8080 -Dserver.shutdown.grace-period=24s
  ports:
  - name: main
    port: 8080
  probes:
    liveness:
      httpGet:
        path: /livez
        port: 8080
        scheme: HTTP
    readiness:
      httpGet:
        path: /readyz
        port: 8080
        scheme: HTTP
    startup:
      failureThreshold: 120
      httpGet:
        path: /readyz
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 1
  relatedRefs:
  - for: kubernetes.list-replicas
    kind: Pod
    labelSelector: containerapp.apps.tanzu.vmware.com/app-name=spring-music-ga
  - apiGroup: apps
    for: kubernetes.service-binding-target
    kind: Deployment
    name: spring-music-ga
  - for: kubernetes.service-target
    kind: Service
    name: spring-music-ga
  - for: kubernetes.scale-replicas
    keyPath: .data['values.yml']->[yaml].replicas
    kind: Secret
    name: spring-music-ga-values
  - for: kubernetes.scale-resources
    keyPath: .data['values.yml']->[yaml].resources
    kind: Secret
    name: spring-music-ga-values
  - for: kubernetes.set-secret-env
    keyPath: .data['values.yml']->[yaml].secretEnv
    kind: Secret
    name: spring-music-ga-values
  - apiGroup: packaging.carvel.dev
    for: kubernetes.delete
    kind: PackageInstall
    name: spring-music-ga
  - apiGroup: data.packaging.carvel.dev
    for: kubernetes.delete
    kind: Package
    name: spring-music-ga.apps.local.20241010.1956.54464
  - for: kubernetes.delete
    kind: Secret
    name: spring-music-ga-values
  - for: kubernetes.set-content-hash
    keyPath: .data['values.yml']->[yaml].contentHash
    kind: Secret
    name: spring-music-ga-values
  - for: kubernetes.set-content-version
    keyPath: .data['values.yml']->[yaml].contentVersion
    kind: Secret
    name: spring-music-ga-values
  resources:
    cpu: 300m
    memory: 1Gi
