apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/spring-music-ga
    containerapp.apps.tanzu.vmware.com/class: kubernetes
  name: spring-music-ga
spec:
  contact:
    team: warroyo
  content:
    buildTimestamp: "2024-09-30T15:43:42Z"
    gitCommit: 7e04e743897dc75ec8ea64725fdfd6192ddc0a01-dirty
    gitURL: github.com/warroyo/spring-music.git
    packageImage: ghcr.io/warroyo/spring-music-ga@sha256:cb6aca3a0bc728a79f0d9ac63e01e25b87fd506f9335a69379f9cfcb4a707982
    packageRefName: spring-music-ga.apps.local
    packageVersion: 20240930.1543.42399
    summary: git:7e04e74 @ 2024-09-30T15:43:42Z
    version: 20240930.1543.42399
  health:
    maxUnavailableReplicas: 10%
  image: ghcr.io/warroyo/spring-music-ga:20240930.1543.42399@sha256:1e979f214e3cc0e330577cbd2fb28a27dd7d40d5cec12ef73bdd258cdd2dffc8
  nonSecretEnv:
  - name: JAVA_TOOL_OPTIONS
    value: -Dmanagement.endpoint.health.probes.add-additional-paths=true -Dmanagement.health.probes.enabled=true
      -Dserver.port=8080 -Dserver.shutdown.grace-period=24s
  ports:
  - name: main
    port: 8080
  probes:
    liveness:
      httpGet:
        path: /livez
        port: 8080
        scheme: HTTP
    readiness:
      httpGet:
        path: /readyz
        port: 8080
        scheme: HTTP
    startup:
      failureThreshold: 120
      httpGet:
        path: /readyz
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 1
  relatedRefs:
  - for: kubernetes.list-replicas
    kind: Pod
    labelSelector: containerapp.apps.tanzu.vmware.com/app-name=spring-music-ga
  - apiGroup: apps
    for: kubernetes.service-binding-target
    kind: Deployment
    name: spring-music-ga
  - for: kubernetes.service-target
    kind: Service
    name: spring-music-ga
  - for: kubernetes.scale-replicas
    keyPath: .data['values.yml']->[yaml].replicas
    kind: Secret
    name: spring-music-ga-values
  - for: kubernetes.scale-resources
    keyPath: .data['values.yml']->[yaml].resources
    kind: Secret
    name: spring-music-ga-values
  - for: kubernetes.set-secret-env
    keyPath: .data['values.yml']->[yaml].secretEnv
    kind: Secret
    name: spring-music-ga-values
  - apiGroup: packaging.carvel.dev
    for: kubernetes.delete
    kind: PackageInstall
    name: spring-music-ga
  - apiGroup: data.packaging.carvel.dev
    for: kubernetes.delete
    kind: Package
    name: spring-music-ga.apps.local.20240930.1543.42399
  - for: kubernetes.delete
    kind: Secret
    name: spring-music-ga-values
  - for: kubernetes.set-content-hash
    keyPath: .data['values.yml']->[yaml].contentHash
    kind: Secret
    name: spring-music-ga-values
  - for: kubernetes.set-content-version
    keyPath: .data['values.yml']->[yaml].contentVersion
    kind: Secret
    name: spring-music-ga-values
  resources:
    cpu: 300m
    memory: 1Gi
