apiVersion: services.tanzu.vmware.com/v1
kind: ServiceBinding
metadata:
  name: azure-db
  namespace: default
spec:
  alias: azure-db
  serviceRef:
    apiGroup: services.tanzu.vmware.com
    connectorName: main
    kind: PreProvisionedService
    name: azuremysql
  targetRef:
    apiGroup: apps.tanzu.vmware.com
    kind: ContainerApp
    name: spring-music-ga