apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/spring-music-ga
  creationTimestamp: null
  name: spring-music-ga.apps.local.20241029.1935.3129
spec:
  refName: spring-music-ga.apps.local
  releasedAt: "2024-10-29T19:38:02Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: us-west1-docker.pkg.dev/fe-cpage/west-sa-build-registry/warroyo/spring-music-ga@sha256:566ddf9c016bb9837bff3e45d4d07f25447886beda8553cddb844ba79a857d3a
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20241029.1935.3129
