apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/spring-music-ga
  creationTimestamp: null
  name: spring-music-ga.apps.local.20240930.1543.42399
spec:
  refName: spring-music-ga.apps.local
  releasedAt: "2024-09-30T15:45:15Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: ghcr.io/warroyo/spring-music-ga@sha256:cb6aca3a0bc728a79f0d9ac63e01e25b87fd506f9335a69379f9cfcb4a707982
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240930.1543.42399
