apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/spring-music-ga
  creationTimestamp: null
  name: spring-music-ga
spec:
  packageRef:
    refName: spring-music-ga.apps.local
    versionSelection:
      constraints: 20241010.1956.54464
  serviceAccountName: carvel-package-installer
  values:
  - secretRef:
      name: spring-music-ga-values
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
