apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/spring-music
    containerapp.apps.tanzu.vmware.com/class: kubernetes
  name: spring-music
spec:
  contact:
    team: warroyo
  content:
    buildTimestamp: "2025-02-14T16:57:42Z"
    gitCommit: 3045044b1d1d6007069a1a168d8d18076cd458a2
    gitRef: supply-chain
    gitURL: github.com/warroyo/spring-music.git
    packageImage: tpsmwarroyo.azurecr.io/apps/warroyo/spring-music@sha256:015d1d7663916372fa3e08e58026e5e8cc1d79ebd3061f7dde942ed544a7fa9f
    packageRefName: spring-music.apps.local
    packageVersion: 20250214.1657.42714
    summary: git:3045044 @ 2025-02-14T16:57:42Z
    version: 20250214.1657.42714
  health:
    maxUnavailableReplicas: 10%
  image: tpsmwarroyo.azurecr.io/apps/warroyo/spring-music:20250214.1657.42714@sha256:5d5dad7591ee719d7b56dc45335050204e4ffe39fce6cc5456ddf55b0374b02b
  nonSecretEnv:
  - name: JAVA_TOOL_OPTIONS
    value: -Dmanagement.endpoint.health.probes.add-additional-paths=true -Dmanagement.endpoints.web.exposure.include=health,info
      -Dmanagement.health.probes.enabled=true -Dmanagement.info.build.enabled=true
      -Dmanagement.info.git.enabled=true -Dmanagement.info.java.enabled=true -Dmanagement.info.os.enabled=true
      -Dmanagement.info.process.enabled=true -Dmanagement.server.port=8081 -Dserver.port=8080
      -Dserver.shutdown.grace-period=24s
  ports:
  - name: main
    port: 8080
    protocol: HTTP
  probes:
    liveness:
      httpGet:
        path: /livez
        port: 8080
        scheme: HTTP
    readiness:
      httpGet:
        path: /readyz
        port: 8080
        scheme: HTTP
    startup:
      failureThreshold: 120
      httpGet:
        path: /readyz
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 1
  relatedRefs:
  - for: kubernetes.list-replicas
    kind: Pod
    labelSelector: containerapp.apps.tanzu.vmware.com/app-name=spring-music
  - apiGroup: apps
    for: kubernetes.service-binding-target
    kind: Deployment
    name: spring-music
  - for: kubernetes.service-target
    kind: Service
    name: spring-music
  - for: kubernetes.scale-replicas
    keyPath: .data['values.yml']->[yaml].replicas
    kind: Secret
    name: spring-music-values
  - for: kubernetes.scale-resources
    keyPath: .data['values.yml']->[yaml].resources
    kind: Secret
    name: spring-music-values
  - for: kubernetes.set-secret-env
    keyPath: .data['values.yml']->[yaml].secretEnv
    kind: Secret
    name: spring-music-values
  - apiGroup: packaging.carvel.dev
    for: kubernetes.delete
    kind: PackageInstall
    name: spring-music
  - apiGroup: data.packaging.carvel.dev
    for: kubernetes.delete
    kind: Package
    name: spring-music.apps.local.20250214.1657.42714
  - for: kubernetes.delete
    kind: Secret
    name: spring-music-values
  - for: kubernetes.set-content-hash
    keyPath: .data['values.yml']->[yaml].contentHash
    kind: Secret
    name: spring-music-values
  - for: kubernetes.set-content-version
    keyPath: .data['values.yml']->[yaml].contentVersion
    kind: Secret
    name: spring-music-values
  resources:
    cpu: 300m
    memory: 1Gi
