apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/spring-music
  creationTimestamp: null
  name: spring-music.apps.local.20250214.1657.42714
spec:
  refName: spring-music.apps.local
  releasedAt: "2025-02-14T16:59:09Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: tpsmwarroyo.azurecr.io/apps/warroyo/spring-music@sha256:015d1d7663916372fa3e08e58026e5e8cc1d79ebd3061f7dde942ed544a7fa9f
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20250214.1657.42714
