apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/spring-music
    containerapp.apps.tanzu.vmware.com/class: kubernetes
  name: spring-music
spec:
  contact:
    team: warroyo
  content:
    buildTimestamp: "2024-12-10T19:16:15Z"
    gitCommit: 2a4f3a95d4b46a1909d9c6bd9b976b42f4f7eab7-dirty
    gitURL: github.com/warroyo/spring-music.git
    packageImage: us-west1-docker.pkg.dev/fe-cpage/west-sa-build-registry/warroyo/spring-music@sha256:7cef7bf103109ae835d0762766f175d7e855bd79578d61b1aa5fc2de6c0688d4
    packageRefName: spring-music.apps.local
    packageVersion: 20241210.1916.15232
    summary: git:2a4f3a9 @ 2024-12-10T19:16:15Z
    version: 20241210.1916.15232
  health:
    maxUnavailableReplicas: 10%
  image: us-west1-docker.pkg.dev/fe-cpage/west-sa-build-registry/warroyo/spring-music:20241210.1916.15232@sha256:906975446b9733e2b79d2633843e80102f76f8883deb9393cdc2d4ea0f76cf94
  nonSecretEnv:
  - name: JAVA_TOOL_OPTIONS
    value: -Dmanagement.endpoint.health.probes.add-additional-paths=true -Dmanagement.endpoints.web.exposure.include=health,info
      -Dmanagement.health.probes.enabled=true -Dmanagement.info.build.enabled=true
      -Dmanagement.info.git.enabled=true -Dmanagement.info.java.enabled=true -Dmanagement.info.os.enabled=true
      -Dmanagement.info.process.enabled=true -Dmanagement.server.port=8081 -Dserver.port=8080
      -Dserver.shutdown.grace-period=24s
  ports:
  - name: main
    port: 8080
    protocol: HTTP
  probes:
    liveness:
      httpGet:
        path: /livez
        port: 8080
        scheme: HTTP
    readiness:
      httpGet:
        path: /readyz
        port: 8080
        scheme: HTTP
    startup:
      failureThreshold: 120
      httpGet:
        path: /readyz
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 1
  relatedRefs:
  - for: kubernetes.list-replicas
    kind: Pod
    labelSelector: containerapp.apps.tanzu.vmware.com/app-name=spring-music
  - apiGroup: apps
    for: kubernetes.service-binding-target
    kind: Deployment
    name: spring-music
  - for: kubernetes.service-target
    kind: Service
    name: spring-music
  - for: kubernetes.scale-replicas
    keyPath: .data['values.yml']->[yaml].replicas
    kind: Secret
    name: spring-music-values
  - for: kubernetes.scale-resources
    keyPath: .data['values.yml']->[yaml].resources
    kind: Secret
    name: spring-music-values
  - for: kubernetes.set-secret-env
    keyPath: .data['values.yml']->[yaml].secretEnv
    kind: Secret
    name: spring-music-values
  - apiGroup: packaging.carvel.dev
    for: kubernetes.delete
    kind: PackageInstall
    name: spring-music
  - apiGroup: data.packaging.carvel.dev
    for: kubernetes.delete
    kind: Package
    name: spring-music.apps.local.20241210.1916.15232
  - for: kubernetes.delete
    kind: Secret
    name: spring-music-values
  - for: kubernetes.set-content-hash
    keyPath: .data['values.yml']->[yaml].contentHash
    kind: Secret
    name: spring-music-values
  - for: kubernetes.set-content-version
    keyPath: .data['values.yml']->[yaml].contentVersion
    kind: Secret
    name: spring-music-values
  resources:
    cpu: 300m
    memory: 1Gi
