apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/spring-music
    containerapp.apps.tanzu.vmware.com/class: kubernetes
  name: spring-music
spec:
  contact:
    team: warroyo
  content:
    buildTimestamp: "2025-01-06T20:56:11Z"
    gitCommit: 747e64d5a390068031ac6cd71c001dc0cb48e61b-dirty
    gitURL: github.com/warroyo/spring-music.git
    packageImage: us-west1-docker.pkg.dev/fe-cpage/west-sa-build-registry/warroyo/spring-music@sha256:92a4fded0b1cd331683dfa786da97a9cb866be46beadaec9263a169f0e7f24cb
    packageRefName: spring-music.apps.local
    packageVersion: 20250106.2056.11913
    summary: git:747e64d @ 2025-01-06T20:56:11Z
    version: 20250106.2056.11913
  health:
    maxUnavailableReplicas: 10%
  image: us-west1-docker.pkg.dev/fe-cpage/west-sa-build-registry/warroyo/spring-music:20250106.2056.11913@sha256:4c53c8dbd0fa26bd66258e53a09e7eb329a15e32cc40cbecea974f259efe66ec
  nonSecretEnv:
  - name: JAVA_TOOL_OPTIONS
    value: -Dmanagement.endpoint.health.probes.add-additional-paths=true -Dmanagement.endpoints.web.exposure.include=health,info
      -Dmanagement.health.probes.enabled=true -Dmanagement.info.build.enabled=true
      -Dmanagement.info.git.enabled=true -Dmanagement.info.java.enabled=true -Dmanagement.info.os.enabled=true
      -Dmanagement.info.process.enabled=true -Dmanagement.server.port=8081 -Dserver.port=8080
      -Dserver.shutdown.grace-period=24s
  ports:
  - name: main
    port: 8080
    protocol: HTTP
  probes:
    liveness:
      httpGet:
        path: /livez
        port: 8080
        scheme: HTTP
    readiness:
      httpGet:
        path: /readyz
        port: 8080
        scheme: HTTP
    startup:
      failureThreshold: 120
      httpGet:
        path: /readyz
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 1
  relatedRefs:
  - for: kubernetes.list-replicas
    kind: Pod
    labelSelector: containerapp.apps.tanzu.vmware.com/app-name=spring-music
  - apiGroup: apps
    for: kubernetes.service-binding-target
    kind: Deployment
    name: spring-music
  - for: kubernetes.service-target
    kind: Service
    name: spring-music
  - for: kubernetes.scale-replicas
    keyPath: .data['values.yml']->[yaml].replicas
    kind: Secret
    name: spring-music-values
  - for: kubernetes.scale-resources
    keyPath: .data['values.yml']->[yaml].resources
    kind: Secret
    name: spring-music-values
  - for: kubernetes.set-secret-env
    keyPath: .data['values.yml']->[yaml].secretEnv
    kind: Secret
    name: spring-music-values
  - apiGroup: packaging.carvel.dev
    for: kubernetes.delete
    kind: PackageInstall
    name: spring-music
  - apiGroup: data.packaging.carvel.dev
    for: kubernetes.delete
    kind: Package
    name: spring-music.apps.local.20250106.2056.11913
  - for: kubernetes.delete
    kind: Secret
    name: spring-music-values
  - for: kubernetes.set-content-hash
    keyPath: .data['values.yml']->[yaml].contentHash
    kind: Secret
    name: spring-music-values
  - for: kubernetes.set-content-version
    keyPath: .data['values.yml']->[yaml].contentVersion
    kind: Secret
    name: spring-music-values
  resources:
    cpu: 300m
    memory: 1Gi
