apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/spring-music
    containerapp.apps.tanzu.vmware.com/class: kubernetes
  name: spring-music
spec:
  contact:
    team: warroyo
  content:
    buildTimestamp: "2025-01-06T23:20:25Z"
    gitCommit: d31ad50b33e2602cfe9d519c5f8e543ce6fd6ff8-dirty
    gitURL: github.com/warroyo/spring-music.git
    packageImage: us-west1-docker.pkg.dev/fe-cpage/west-sa-build-registry/warroyo/spring-music@sha256:06d08a3b1548867e7f358126a4d415a9559120c1e886360fbcc6aa2102e047e5
    packageRefName: spring-music.apps.local
    packageVersion: 20250106.2320.25536
    summary: git:d31ad50 @ 2025-01-06T23:20:25Z
    version: 20250106.2320.25536
  health:
    maxUnavailableReplicas: 10%
  image: us-west1-docker.pkg.dev/fe-cpage/west-sa-build-registry/warroyo/spring-music:20250106.2320.25536@sha256:247f75fd10c3e4a72878f8367faa5e7dbaade99688a7e09bfea58e233fdfee9b
  nonSecretEnv:
  - name: JAVA_TOOL_OPTIONS
    value: -Dmanagement.endpoint.health.probes.add-additional-paths=true -Dmanagement.endpoints.web.exposure.include=health,info
      -Dmanagement.health.probes.enabled=true -Dmanagement.info.build.enabled=true
      -Dmanagement.info.git.enabled=true -Dmanagement.info.java.enabled=true -Dmanagement.info.os.enabled=true
      -Dmanagement.info.process.enabled=true -Dmanagement.server.port=8081 -Dserver.port=8080
      -Dserver.shutdown.grace-period=24s
  ports:
  - name: main
    port: 8080
    protocol: HTTP
  probes:
    liveness:
      httpGet:
        path: /livez
        port: 8080
        scheme: HTTP
    readiness:
      httpGet:
        path: /readyz
        port: 8080
        scheme: HTTP
    startup:
      failureThreshold: 120
      httpGet:
        path: /readyz
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 1
  relatedRefs:
  - for: kubernetes.list-replicas
    kind: Pod
    labelSelector: containerapp.apps.tanzu.vmware.com/app-name=spring-music
  - apiGroup: apps
    for: kubernetes.service-binding-target
    kind: Deployment
    name: spring-music
  - for: kubernetes.service-target
    kind: Service
    name: spring-music
  - for: kubernetes.scale-replicas
    keyPath: .data['values.yml']->[yaml].replicas
    kind: Secret
    name: spring-music-values
  - for: kubernetes.scale-resources
    keyPath: .data['values.yml']->[yaml].resources
    kind: Secret
    name: spring-music-values
  - for: kubernetes.set-secret-env
    keyPath: .data['values.yml']->[yaml].secretEnv
    kind: Secret
    name: spring-music-values
  - apiGroup: packaging.carvel.dev
    for: kubernetes.delete
    kind: PackageInstall
    name: spring-music
  - apiGroup: data.packaging.carvel.dev
    for: kubernetes.delete
    kind: Package
    name: spring-music.apps.local.20250106.2320.25536
  - for: kubernetes.delete
    kind: Secret
    name: spring-music-values
  - for: kubernetes.set-content-hash
    keyPath: .data['values.yml']->[yaml].contentHash
    kind: Secret
    name: spring-music-values
  - for: kubernetes.set-content-version
    keyPath: .data['values.yml']->[yaml].contentVersion
    kind: Secret
    name: spring-music-values
  resources:
    cpu: 300m
    memory: 1Gi
