apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/spring-music
  creationTimestamp: null
  name: spring-music.apps.local.20241210.1916.15232
spec:
  refName: spring-music.apps.local
  releasedAt: "2024-12-10T19:19:51Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: us-west1-docker.pkg.dev/fe-cpage/west-sa-build-registry/warroyo/spring-music@sha256:7cef7bf103109ae835d0762766f175d7e855bd79578d61b1aa5fc2de6c0688d4
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20241210.1916.15232
