apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/spring-music
  creationTimestamp: null
  name: spring-music.apps.local.20250106.2320.25536
spec:
  refName: spring-music.apps.local
  releasedAt: "2025-01-06T23:24:10Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: us-west1-docker.pkg.dev/fe-cpage/west-sa-build-registry/warroyo/spring-music@sha256:06d08a3b1548867e7f358126a4d415a9559120c1e886360fbcc6aa2102e047e5
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20250106.2320.25536
